dist: bionic
language: node_js
node_js:
  - '10'
  - '12'
  - node

addons:
  apt:
    packages:
      - asciidoctor
      - pandoc

cache:
  yarn: true
  npm: false

install:
  - yarn install

script:
  - yarn build
  - yarn test
  - yarn lint
  - yarn readme2md

deploy:
  provider: npm
  email: jakub@jirutka.cz
  api_key:
    secure: "LyFGE8GFST+Scddx6rntPvW8cMWgAADlUWn1mpMYx8iFzbTLA5x7KuZPSPJVQBMof/0vH1jlNAMVFM3MHYbrKM4e96Ig+TzSa5jtO0galF+5XLeHo1MOIC3RBm7Le2XcWJ9TIaCBg8+FMGS+d/toRJgiCIkzzS1tDxAQOf6pV3HiYcMXFLAe4YskyC5KvXk41alNLbaNUleD7yJcwDY8Iim2QGB978AhsGVvpVMdP6rC3Q65CHuH65czPkoPuBqQjA1tLml8qwYz0y0IXuciw1Ld6AGxAfulHJ6UgtAFjgIVGEzBoCiQUjY+CAcZYzHzy01VxDahDgsAAqLOM+s0k1fc4lVeTgwKB48A9FEWcuu+a4nMAGPtNt8Mg4BSCv3qNo6veHmLpzt8MVNv08pwnTRKawCCzQkfJHXv5b73fMGZRGBN8jan1nPzhMKYzyxmFQAHrU1sIUErLOXT9+3aAQV2ASe6sAZge5CRV+D2nL9xGusOi9W/0qf6+MaGs08qvcBPSOvm6ObvYcNuAXfNSaFQNUdDPGeRx5qiLt32wP8oWDEc2ou8V6KddJR4EBlcGUlSLwC2qT7axyqm3a57F/WpD0f4xWRFPOPGEeID2se8hyJFvQrox8580aWlIMzZ8jWs7G3LFIKLnCdb76J1ksDjSQpOPLY8bh0M+jQIuxo="  # a49c......e2d3
  skip_cleanup: true
  on:
    tags: true
    node_js: '10'
