name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }}"
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
          - lts/*
          - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn lint

      - run: sudo apt-get install asciidoctor pandoc
      - run: yarn readme2md

  publish:
    name: Publish to npmjs
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get install asciidoctor pandoc

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
